# Generated by Django 4.2.6 on 2024-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
