# Generated by Django 4.2.6 on 2024-12-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0004_remove_lawyer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
    ]
