# Generated by Django 4.2.6 on 2025-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0007_expert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='company',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
