# Generated by Django 4.2.6 on 2025-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0008_content_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='company',
        ),
        migrations.AddField(
            model_name='incident',
            name='company',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
